### ISSUE TITLE
Sample repo or a a guide for getting this working in aws?

### ISSUE THREAD

**Issue by bostondevin** [MikeBild/sveltekit-adapter-aws#1]
Do you have a little setup guide for this or an example repo? I swapped this in, but haven't been able to get it working yet - probably all the aws setup i'm not doing right...

**Comment by MikeBild** [comment]
Thank you! Yes, I'll prepare a guide and a little example in the next week. 

What does not working as expected from your perspective?

**Comment by bostondevin** [comment]
I was wondering how you are getting it deployed - seems to be different ways to do that with aws - fargate, serverless, s3, etc. I was hoping to run a build or deploy command and it would magically publish it to AWS :)

**Comment by bostondevin** [comment]
Also, i get this error:

> Using adapter-awscdk
✘ [ERROR] Could not resolve "@sveltejs/kit/install-fetch"

    build/server/shims.js:1:50:
      1 │ export { fetch, Response, Request, Headers } from '@sveltejs/kit/install-fetch';
        ╵                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./install-fetch" is not exported by package "@sveltejs/kit":
