### ISSUE TITLE
Adding additional policy statements to serverHandler

### ISSUE THREAD

**Issue by CalebBassham** [MikeBild/sveltekit-adapter-aws#14]
**Is your feature request related to a problem? Please describe.**

I would like to be able to add additional policy statements to the `serverHandler`. Useful if using other AWS resources such as s3. In that case it could be nice to allow the `s3:GetObject` action for a bucket, so that you can fetch a file for a user for example.

**Describe the solution you'd like**

Probably add some sort of policy statement array to AWSAdapterStackProps.

**Describe alternatives you've considered**

Haven't really thought of a better solution.

**Comment by MikeBild** [comment]
solved by #15
