### ISSUE TITLE
sample infrastructure.js?

### ISSUE THREAD

**Issue by bostondevin** [MikeBild/sveltekit-adapter-aws#2]
Is there an example of the infrastructure.js file?

**Comment by MikeBild** [comment]
I'm currently creating two different repos to create a simple and an advanced example. Stay tuned - I need a few more hours. Thank you!

**Comment by MikeBild** [comment]
I just build an example that creates a DynamoDB table (`infrastructure.js`) and fetches data from them (`data.svelte`). A deployed example is [here](https://github.com/MikeBild/sveltekit-adapter-aws-advanced-example).
