### ISSUE TITLE
Suggestion: Replace API Gateway with Lambda Function URL

### ISSUE THREAD

**Issue by willfarrell** [MikeBild/sveltekit-adapter-aws#7]
**Is your feature request related to a problem? Please describe.**
No problem. But, has a performance improvement, decrease resources needed during deploy, and allows longer than a 30sec timeout (up to 15min).

**Describe the solution you'd like**
With recent release of Lambda Function URLs, it's no longer needed to have an API Gateway for a single lambda to ensure it receives a parsed event.

**Describe alternatives you've considered**
I use this approach, but deployed with terraform.

**Additional context**
https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/

**Comment by MikeBild** [comment]
Hi Will,

thank you. I already had that in mind. Unfortunately, the Lambda URL does not offer the option of custom domain binding and all the other possibilities of the HTTP API Gateway like multiple stages, Cognito and custom authorizer functions. This is helpful especially in the context of additional CDK-based AWS resources bound to deployed stack. (https://github.com/MikeBild/sveltekit-adapter-aws-advanced-example/blob/master/infrastructure/deploy.js)
